import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import axios from "axios";

const Home: NextPage = () => {
    const CLOUDINARY_URL = "https://api.cloudinary.com/v1_1/depnwyeqs";
    const fileRef = React.useRef<HTMLInputElement>(null);

    const submit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        if (!fileRef.current?.files) return;

        console.log(fileRef.current.files[0] as Blob);
        const formdata = new FormData();
        formdata.append("file", fileRef.current.files[0] as Blob);

        const data = await axios
            .post(CLOUDINARY_URL + "image/upload", formdata)
            .then((res) => console.log(res))
            .catch((err) => console.log(err));
    };

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <form onSubmit={(e) => void submit(e)}>
                    <input type="file" ref={fileRef} />
                    <input type="submit" />
                </form>
            </main>
        </>
    );
};

export default Home;
